# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - echo Installing dependencies...
#       - npm install
#   build:
#     commands:
#       - echo Zipping function...
#       - zip -r function.zip index.js node_modules/  # Add other files as needed
# artifacts:
#   files:
#     - function.zip


version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Updating apt and installing MySQL client & server..."
      - apt-get update
      - apt-get install -y mysql-client mysql-server

  build:
    commands:
      - echo "Running health check script..."
      - node index.js
