# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - echo Installing dependencies...
#       - npm install
#   build:
#     commands:
#       - echo Zipping function...
#       - zip -r function.zip index.js node_modules/  # Add other files as needed
# artifacts:
#   files:
#     - function.zip


version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
      - echo "Checking internet connection..."
      - ping -c 4 google.com  # Test internet connection
      - echo "Internet is online"
      
      - echo "Updating package lists..."
      - apt-get update  # Ensure apt package lists are updated
      - echo "Installing MySQL client..."
      - apt-get install -y mysql-client  # Install MySQL client on Ubuntu
      - echo "Testing database connection..."
      - mysql -h $DB_HOST -u $DB_USER -p$DB_PASSWORD -e "SELECT 1;"  # Test MySQL connection
      - echo "Database connected successfully"
  build:
    commands:
      - echo Zipping function...
      - zip -r function.zip index.js node_modules/  # Add other files as needed
artifacts:
  files:
    - function.zip
