# version: 0.2

# phases:
#   install:
#     runtime-versions:
#       nodejs: 18
#     commands:
#       - echo Installing dependencies...
#       - npm install
#   build:
#     commands:
#       - echo Zipping function...
#       - zip -r function.zip index.js node_modules/  # Add other files as needed
# artifacts:
#   files:
#     - function.zip


version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running health check with Express..."
      - node index.js &
      - sleep 2
      - curl http://localhost:3000

artifacts:
  files:
    - '**/*'
